name: Python CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Run Tests
              run: python -m unittest discover

            - name: Run Security Scan
              run: |
                  python -m pip install bandit
                  python -m bandit -r .
